
package mtomupload;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MTOMCustomer", targetNamespace = "http://MTOMUpload/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface MTOMCustomer {


    /**
     * 
     * @param customer
     */
    @WebMethod
    public void uploadCustomerByName(
        @WebParam(name = "customer", partName = "customer")
        Customer customer);

}
