
package serviceimpl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "userAuthorizationService", targetNamespace = "http://serviceImpl/", wsdlLocation = "http://localhost:8080/jax_ws/UserAuthorizationService?wsdl")
public class UserAuthorizationService
    extends Service
{

    private final static URL USERAUTHORIZATIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException USERAUTHORIZATIONSERVICE_EXCEPTION;
    private final static QName USERAUTHORIZATIONSERVICE_QNAME = new QName("http://serviceImpl/", "userAuthorizationService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/jax_ws/UserAuthorizationService?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        USERAUTHORIZATIONSERVICE_WSDL_LOCATION = url;
        USERAUTHORIZATIONSERVICE_EXCEPTION = e;
    }

    public UserAuthorizationService() {
        super(__getWsdlLocation(), USERAUTHORIZATIONSERVICE_QNAME);
    }

    public UserAuthorizationService(WebServiceFeature... features) {
        super(__getWsdlLocation(), USERAUTHORIZATIONSERVICE_QNAME, features);
    }

    public UserAuthorizationService(URL wsdlLocation) {
        super(wsdlLocation, USERAUTHORIZATIONSERVICE_QNAME);
    }

    public UserAuthorizationService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, USERAUTHORIZATIONSERVICE_QNAME, features);
    }

    public UserAuthorizationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UserAuthorizationService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UserAuthorization
     */
    @WebEndpoint(name = "userAuthorizationPort")
    public UserAuthorization getUserAuthorizationPort() {
        return super.getPort(new QName("http://serviceImpl/", "userAuthorizationPort"), UserAuthorization.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UserAuthorization
     */
    @WebEndpoint(name = "userAuthorizationPort")
    public UserAuthorization getUserAuthorizationPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://serviceImpl/", "userAuthorizationPort"), UserAuthorization.class, features);
    }

    private static URL __getWsdlLocation() {
        if (USERAUTHORIZATIONSERVICE_EXCEPTION!= null) {
            throw USERAUTHORIZATIONSERVICE_EXCEPTION;
        }
        return USERAUTHORIZATIONSERVICE_WSDL_LOCATION;
    }

}
