
package com.eutesttools;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This is a test web service for enduser test purpose
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EUWS", targetNamespace = "http://www.eutesttools.com", wsdlLocation = "http://10.8.255.231/WebServices/EUWS.asmx?WSDL")
public class EUWS
    extends Service
{

    private final static URL EUWS_WSDL_LOCATION;
    private final static WebServiceException EUWS_EXCEPTION;
    private final static QName EUWS_QNAME = new QName("http://www.eutesttools.com", "EUWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.8.255.231/WebServices/EUWS.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        EUWS_WSDL_LOCATION = url;
        EUWS_EXCEPTION = e;
    }

    public EUWS() {
        super(__getWsdlLocation(), EUWS_QNAME);
    }

    public EUWS(WebServiceFeature... features) {
        super(__getWsdlLocation(), EUWS_QNAME, features);
    }

    public EUWS(URL wsdlLocation) {
        super(wsdlLocation, EUWS_QNAME);
    }

    public EUWS(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, EUWS_QNAME, features);
    }

    public EUWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EUWS(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EUWSSoap
     */
    @WebEndpoint(name = "EUWSSoap")
    public EUWSSoap getEUWSSoap() {
        return super.getPort(new QName("http://www.eutesttools.com", "EUWSSoap"), EUWSSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EUWSSoap
     */
    @WebEndpoint(name = "EUWSSoap")
    public EUWSSoap getEUWSSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.eutesttools.com", "EUWSSoap"), EUWSSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (EUWS_EXCEPTION!= null) {
            throw EUWS_EXCEPTION;
        }
        return EUWS_WSDL_LOCATION;
    }

}
